Add build-script notes

diff --git a/build-scripts/grcm39/genome/gencode b/build-scripts/grcm39/genome/gencode
--- a/build-scripts/grcm39/genome/gencode
+++ b/build-scripts/grcm39/genome/gencode
@@ -3,6 +3,7 @@
 #WHATIS:GRCm39 reference genome FASTA
 #URL:https://www.gencodegenes.org/mouse/
 #ENV:GENOME_FASTA=$app_root/GRCm39.primary_assembly.genome.fa
+#ENVNOTE:GRCm39 reference genome
 
 install_app() {
     # By default, $target_dir and $tmp_dir are created and we are now in $tmp_dir
@@ -28,6 +29,7 @@ install_app() {
 # - target_dir:       opt/assembly/data_type/version (set by condatainer)
 # - tmp_dir:          tmp directory (set by condatainer)
 
+set -e # exit on error
 RED='\033[0;91m'    # Red      WARNING or ERROR
 BLUE='\033[0;94m'   # Blue     Dependency or Modulefile Changes
 YELLOW='\033[0;93m' # Yellow   App Name and/or Version
@@ -92,9 +94,7 @@ tar_xf_pigz() {
 }
 #endregion
 
-install
-    fi
-
+install() {
     if [[ -z "$tmp_dir" ]]; then
         print_stderr "${RED}ERROR${NC}: tmp_dir is not set!"
         print_stderr "Exit Installing"
